name: Updating Detections

on:
  push:
    paths:
      - '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
    

